(function(){
if(window.__GJ_AUTH_V105_LOADED__)return;window.__GJ_AUTH_V105_LOADED__=true;
const URL='https://fcnsglahkjvhyfkghnpy.supabase.co',KEY='sb_publishable_dUtfbI9RAAwDCUBKJjjMCQ_kqIeg-ew';
const sb=window.supabase?.createClient(URL,KEY);
window.GJ_AUTH={sb,profile:null,isAdmin:false,workspaceUserId:null,impersonating:false};window.GJ_WORKSPACE_ID=()=>GJ_AUTH.workspaceUserId||GJ_AUTH.profile?.id||null;
const REMEMBER_KEY='gj_login_remember_v1',SESSION_KEY='gj_app_open_session';
const saved=(()=>{try{return JSON.parse(localStorage.getItem(REMEMBER_KEY)||'null')}catch{return null}})();
const lang=localStorage.getItem('gj_app_language')||'nl',TX={nl:['Log in om verder te gaan','E-mailadres','Wachtwoord','E-mailadres en wachtwoord onthouden','Inloggen','Wachtwoord vergeten','De onthouden gegevens worden alleen op dit apparaat opgeslagen.'],en:['Sign in to continue','Email address','Password','Remember email address and password','Sign in','Forgot password','Remembered details are stored only on this device.'],de:['Anmelden, um fortzufahren','E-Mail-Adresse','Passwort','E-Mail-Adresse und Passwort speichern','Anmelden','Passwort vergessen','Die gespeicherten Daten werden nur auf diesem Gerät abgelegt.']},x=TX[lang]||TX.nl;
document.head.insertAdjacentHTML('beforeend',`<style>#gjAuthGate{position:fixed;inset:0;z-index:999999;background:linear-gradient(145deg,#123b73,#082b63 58%,#061f49);display:flex;align-items:center;justify-content:center;padding:20px;font-family:Arial,sans-serif}#gjAuthCard{width:min(420px,100%);background:#fff;border-radius:22px;padding:24px;box-shadow:0 25px 70px #001a3d99}.gjLogo{display:block;width:138px;max-height:124px;object-fit:contain;margin:0 auto 14px}.gjSub{text-align:center;color:#667085;margin:2px 0 20px;font-weight:700}.gjField{display:grid;gap:6px;margin:11px 0;font-weight:800;color:#102a43}.gjField input{font:inherit;padding:12px;border:1px solid #cbd5e1;border-radius:11px}.gjRemember{display:flex;align-items:center;gap:8px;margin:10px 0;color:#334155;font-size:14px;font-weight:700}.gjRemember input{width:18px;height:18px}.gjBtn{width:100%;border:1px solid #d9e0e8;border-radius:12px;padding:12px;font:inherit;font-weight:900;background:#123b73;color:#d9e0e8;margin-top:8px}.gjBtn.secondary{background:#f8fafc;color:#123b73}.gjMsg{min-height:22px;color:#b42318;margin-top:10px;text-align:center}.gjSecurity{font-size:11px;color:#64748b;text-align:center;margin-top:8px}.gjUserBar{display:none!important}.gjAdminOnly{display:none!important}body.gj-admin .gjAdminOnly{display:block!important}body.gj-admin button.gjAdminOnly{display:flex!important}</style>`);
document.body.insertAdjacentHTML('beforeend',`<div id="gjAuthGate"><div id="gjAuthCard"><img src="logo-login.png?v=10500" class="gjLogo" alt="Planning-GJsystems"><div class="gjSub">${x[0]}</div><label class="gjField">${x[1]}<input id="gjEmail" type="email" autocomplete="username"></label><label class="gjField">${x[2]}<input id="gjPassword" type="password" autocomplete="current-password"></label><label class="gjRemember"><input id="gjRemember" type="checkbox"> ${x[3]}</label><button id="gjLogin" class="gjBtn">${x[4]}</button><button id="gjReset" class="gjBtn secondary">${x[5]}</button><div id="gjMsg" class="gjMsg"></div><div class="gjSecurity">${x[6]}</div></div></div>`);
const emailEl=document.getElementById('gjEmail'),passwordEl=document.getElementById('gjPassword'),rememberEl=document.getElementById('gjRemember'),msg=t=>document.getElementById('gjMsg').textContent=t||'';
if(saved?.remember){emailEl.value=saved.email||'';passwordEl.value=saved.password||'';rememberEl.checked=true}
async function profileFor(user){let {data,error}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;const m=user.user_metadata||{};if(!data){const row={id:user.id,email:user.email,first_name:m.first_name||'',last_name:m.last_name||'',full_name:m.full_name||user.email,role:'user',is_active:true};const r=await sb.from('profiles').upsert(row).select().single();if(r.error)throw r.error;data=r.data}data.role=String(data.role).toLowerCase()==='admin'?'admin':'user';return data}
async function openApp(session){const p=await profileFor(session.user);if(p.is_active===false){await sb.auth.signOut();throw new Error('Dit account is uitgeschakeld.')}const roleCheck=await sb.rpc('is_app_admin');if(roleCheck.error)throw new Error('De centrale rolcontrole kon niet worden geladen. Voer SUPABASE_V10_5_COMPLETE.sql uit.');const isAdmin=roleCheck.data===true;GJ_AUTH.profile=p;GJ_AUTH.isAdmin=isAdmin;const imp=isAdmin?sessionStorage.getItem('gj_impersonate_user_v102'):null;GJ_AUTH.workspaceUserId=imp||p.id;GJ_AUTH.impersonating=!!imp;const wk=GJ_AUTH.workspaceUserId;sessionStorage.setItem('gj_workspace_storage_id',wk);document.body.classList.toggle('gj-admin',isAdmin);document.getElementById('gjAuthGate').style.display='none';window.dispatchEvent(new CustomEvent('gj-auth-ready',{detail:{profile:p,isAdmin,workspaceUserId:wk}}))}
async function boot(){if(!sb){msg('Supabase kon niet worden geladen.');return}const allowed=sessionStorage.getItem(SESSION_KEY)==='1',r=await sb.auth.getSession();if(allowed&&r.data.session){try{await openApp(r.data.session)}catch(e){msg(e.message)}}else if(r.data.session)await sb.auth.signOut()}
document.getElementById('gjLogin').onclick=async()=>{try{msg('Bezig met inloggen...');const email=emailEl.value.trim(),password=passwordEl.value,r=await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(rememberEl.checked)localStorage.setItem(REMEMBER_KEY,JSON.stringify({remember:true,email,password}));else localStorage.removeItem(REMEMBER_KEY);sessionStorage.setItem(SESSION_KEY,'1');await openApp(r.data.session)}catch(e){msg(e.message)}};
document.getElementById('gjReset').onclick=async()=>{try{const email=emailEl.value.trim();if(!email)throw new Error('Vul eerst je e-mailadres in.');const r=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(r.error)throw r.error;msg('Herstellink is verstuurd.')}catch(e){msg(e.message)}};boot();
})();
/* Planning-GJsystems v10.5 */
